# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 08:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 3, 8, 45, 31, 516000, tzinfo=utc)),
        ),
    ]
